### PR TITLE
Pranshul

### PR DESCRIPTION
**Pull request by Pranshul-Thakur**
> setup an error handling procedure in setup_vectorstore
> also setup an error Handling in get_relevant_document
> and added warning for missing files

### CODE REVIEW

**Comment by chimosky** [comment]
There's no need to setup the error handling you're trying to setup, what did you notice when trying to test this and can you share steps to reproduce?

**Comment by Pranshul-Thakur** [comment]
i added the error handling part for better clarity while trying to run it and the output i was getting it while trying it out was as follows 
image
prior to this while running the original one, i kept getting undefined errors

**Comment by chimosky** [comment]
An undefined errror could means the package import didn't work, maybe because you didn't have the dependency installed.

In the case of the image you've shared above - you could share text next time as that's clearer -, `qa_chain` is created on [L109](https://github.com/sugarlabs/sugar-ai/blob/main/rag_agent.py#L109) before it's used anywhere.

@kshitijdshah99 can you reproduce this?

**Comment by Pranshul-Thakur** [comment]
ok, i ll try reinstalling it all and doing it again, and get back one i got it working

**Comment by kshitijdshah99** [comment]
> An undefined errror could means the package import didn't work, maybe because you didn't have the dependency installed.
> 
> In the case of the image you've shared above - you could share text next time as that's clearer -, `qa_chain` is created on [L109](https://github.com/sugarlabs/sugar-ai/blob/main/rag_agent.py#L109) before it's used anywhere.
> 
> @kshitijdshah99 can you reproduce this?

Yes even I feel the same maybe there's some issue with the dependencies or their incompatibility. Bcz when I had worked with with it the model was working great. It's the langchain dependencies that are causing this trouble.

**Comment by kshitijdshah99** [comment]
> `qa_chain` is created on [L109](https://github.com/sugarlabs/sugar-ai/blob/main/rag_agent.py#L109) before it's used anywhere.
> 
> @kshitijdshah99 can you reproduce this?

You mean that I initialize the qa_chain only after the query comes in and the document is retrieved?

**Comment by chimosky** [comment]
> the undefined error was because of connection issue, sorry for that

Thanks for the update, closing this now as it's not something we want.

**Pull request closed without merging**
