### PR TITLE
Review - Improve changes and move to rag_agent

### PR DESCRIPTION
**Pull request by chimosky**
Move RAG logic to a new file, use a class
for the functionalities.

Combine requirements.txt, no need for two separate files.

**TODO**
- [x] Migrate from RetrivevalQA as it's [deprecated](https://python.langchain.com/v0.2/docs/versions/migrating_chains/retrieval_qa/).
- [x] Make sure langchain tools used are up to date.
- [x] Create docs folder and add docs for RAG there.
- [x] `self.prompt` seems to be unused, why? I'm guessing migrating from RetrievalQA might solve this.
- [x] Redirect output to right sources instead of using print statements.

@kshitijdshah99 @XXXJumpingFrogXXX kindly review.
I'll leave the other changes to you Kshitij.

This PR is open and we'll use it to track the **TODO** above, and will merge once you've made the necessary changes.

### CODE REVIEW

**Comment by kshitijdshah99** [comment]
@chimosky  I am not sure about dependencies because using ``` pip freeze ``` command I am receiving these set of dependencies in my conda environment and actually a lot of them are interconnected what shall I do 

```
aiohappyeyeballs==2.3.5
aiohttp==3.10.3
aiosignal==1.3.1
altair==5.4.0
annotated-types==0.7.0
anyio==4.4.0
attrs==24.2.0
blinker==1.8.2
cachetools==5.4.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
dataclasses-json==0.6.7
faiss-cpu==1.8.0.post1
filelock==3.15.4
frozenlist==1.4.1
fsspec==2024.6.1
gitdb==4.0.11
GitPython==3.1.43
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.24.5
idna==3.7
Jinja2==3.1.4
joblib==1.4.2
jsonpatch==1.33
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
langchain==0.2.14
langchain-community==0.2.12
langchain-core==0.2.32
langchain-experimental==0.0.64
langchain-ollama==0.1.1
langchain-text-splitters==0.2.2
langsmith==0.1.99
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.3
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.5
mypy-extensions==1.0.0
narwhals==1.4.1
networkx==3.3
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
ollama==0.3.1
orjson==3.10.7
packaging==24.1
pandas==2.2.2
pillow==10.4.0
protobuf==5.27.3
pyarrow==17.0.0
pydantic==2.8.2
pydantic_core==2.20.1
pydeck==0.9.1
Pygments==2.18.0
PyMuPDF==1.24.9
PyMuPDFb==1.24.9
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.2
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rich==13.7.1
rpds-py==0.20.0
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.0
sentence-transformers==3.0.1
setuptools==72.1.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
SQLAlchemy==2.0.32
streamlit==1.37.1
sympy==1.13.2
tenacity==8.5.0
threadpoolctl==3.5.0
tokenizers==0.19.1
toml==0.10.2
torch==2.4.0
tornado==6.4.1
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
watchdog==4.0.2
wheel==0.43.0
yarl==1.9.4
```

**Comment by kshitijdshah99** [comment]
@chimosky @walterbender I am almost done with other changes you asked me in the TODO.
I have modified the RAG a little bit and enhanced it such that it answer's only coding queries of kids and no other queries.

I have implemented it currently using this where it checks for some keywords in this list and based on that it determines if kids query if coding based or redundant. This is just a basic layout I am planning to scale it even further but later after integration is done. If we want we can ignore this part too, let me know your opinions?

```
coding_keywords = [
    'code', 'Python', 'bug', 'error', 'exception', 'syntax', 'Pygame', 'debug', 
    'program', 'programming', 'variable', 'loop', 'if', 'function', 'print', 
    'input', 'string', 'number', 'list', 'tuple', 'dictionary', 'module', 
    'import', 'turtle', 'indentation', 'syntax', 'Pygame', 'math', 'shape', 
    'for', 'while', 'repeat', 'class', 'object', 'method', 'attribute', 
    'operator', 'condition', 'true', 'false', 'boolean', 'integer', 'float', 
    'error', 'bug', 'debug', 'fix', 'type', 'index', 'range', 'len', 'append', 
    'pop', 'remove', 'sort', 'reverse', 'random', 'sleep', 'time', 'pygame', 
    'turtle', 'function', 'variable', 'list', 'loop', 'error', 'syntax', 
    'module', 'import', 'return', 'break', 'continue', 'GTK', 'logic', 'numbers'
]
```

**Comment by walterbender** [comment]
How do you use the keyword list? I presume it will be extended?

**Comment by kshitijdshah99** [comment]
It checks whether child's query contains words present in the list if yes then it answers them. Yes I think it will be extended, because for even advanced tools like chatGPT I tried opening a Python assistant and asked some non coding questions they too answered them, hence I feel advocating this method would be good in our case(as we are dealing with kids and we can't provide them redundant answers).

**Comment by chimosky** [comment]
Answering only coding queries doesn't make much sense to me and shouldn't be something we aim for.

Like you mentioned above, what happens when there are non code related queries if we restrict the responses to just code based queries?

**Comment by kshitijdshah99** [comment]
Yeah I skipped the changes you made on your branch I misunderstood for the main. I feel we can make this chatbot generic too I have no issue with that but the purpose why it's placed inside Pippy is that it generates code itself and not deviate from it's purpose, by code I mean that it will also provide explanation, examples and relevant code snippet. @walterbender what's your opinion on this?
I'll make the other changes soon as you directed.

**Comment by chimosky** [comment]
> "...but the purpose why it's placed inside Pippy is that it generates code itself and not deviate from it's purpose, by code I mean that it will also provide explanation, examples and relevant code snippet..."

I don't understand what you mean by this, could you explain better?

**Comment by kshitijdshah99** [comment]
> > "...but the purpose why it's placed inside Pippy is that it generates code itself and not deviate from it's purpose, by code I mean that it will also provide explanation, examples and relevant code snippet..."
> 
> I don't understand what you mean by this, could you explain better?

I mean that the way we have an AI-assistant in chat Activity for chatting purpose similarly this bot would be exclusively restricted to coding and python learning purpose. Bcz making it generic would loose it's value as it's placed in Pippy itself so the domain it's operating in must be specific.

**Comment by chimosky** [comment]
> I mean that the way we have an AI-assistant in chat Activity for chatting purpose similarly this bot would be exclusively restricted to coding and python learning purpose. Bcz making it generic would loose it's value as it's placed in Pippy itself so the domain it's operating in must be specific.

I got that part, doesn't make it a great reason to place it inside a Pippy folder, the `rag_agent` file does the job perfectly. We can keep any functionality this bot and the chatbot shares together and any other thing separate.

**Comment by kshitijdshah99** [comment]
I have looked out for the dependencies of langchain they are quite updated not latest because on updating some it's giving conflicts with others, currently it's working great.

> langchain==0.3.3
> langchain-community==0.3.2
> langchain-core==0.3.10
> langchain-experimental==0.3.2
> langchain-huggingface==0.1.0
> langchain-ollama==0.2.0
> langchain-text-splitters==0.3.0
> langsmith==0.1.132

**Comment by chimosky** [comment]
Reviewed, opened a PR that needs your attention.

**Comment by chimosky** [comment]
@kshitijdshah99 please review e1ab999, as I've updated the dependencies with the list you sent above.

**Comment by chimosky** [comment]
Seems I'd already made the change in #8, I'll drop the commit.

@XXXJumpingFrogXXX this would be a great time to respond to the comments in that PR.

**Comment by kshitijdshah99** [comment]
> @kshitijdshah99 please review [e1ab999](https://github.com/sugarlabs/sugar-ai/commit/e1ab999b698c2396f464b9e1f3b09b7b48713d47), as I've updated the dependencies with the list you sent above.

Can you add these too?
```
faiss-cpu==1.9.0
sentence-transformers==3.1.1
torch==2.4.1
transformers==4.45.2
PyMuPDF==1.24.11
huggingface-hub==0.25.2
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.77
nvidia-nvtx-cu12==12.1.105
ollama==0.3.3
```
IG the nvidia ones dependencies can be excluded as of now but others are quite important. Mostly these nvidia ones get auto-downloaded with langchain dependencies.

**Comment by chimosky** [comment]
I've made the changes you mentioned, please review.

**Comment by kshitijdshah99** [comment]
yeah it's proper

**Comment by chimosky** [comment]
Seems good, thanks.

**Pull request merged**
